### ISSUE TITLE
Create clean/ca/hayward_pd.py

### ISSUE THREAD

**Issue by stucka** [biglocalnews/clean-scraper#129]
## Additional details
Getting Hayward PD will require GovQA platform code #128 , with Hayward as (one of) the inaugural examples.

## Related pull request(s)

- #128

**Comment by stucka** [comment]
Hayward draft code and sample metadata output is available.

**Comment by tarakc02** [comment]
This was a one-off, we ran it and uploaded the files to our case files repo.
