### ISSUE TITLE
Establish secure credential system

### ISSUE THREAD

**Issue by stucka** [biglocalnews/clean-scraper#130]
## Additional details

Some of our scrapers will require use of usernames and/or passwords to access particular agencies' data (GovQA and Muckrock sites among them, I believe). This project does not yet have an established method to maintain these credentials in a secure method.

Something like Azure Key Vault should be significantly more secure than, say, a private Github repo that gets imported with a token stored in the runtime environments. I have worked on other projects that used Google Artifact Registry. I don't know what the best way forward is, particularly given the heterogeneous nature of the institutions behind this scraper suite and their preferred technology stacks.

## Related pull request(s)

- #128 identified a (potential) need within GovQA scrapers

**Comment by newsroomdev** [comment]
Hey @stucka, Key Vault totally works for the automation environment, and Autofolio is currently using it for its secrets. You can just ping me when you have the credentials to add

**Comment by stucka** [comment]
There's a partial implementation in #120 for utils.get_credentials that will try to return results from a locally stored JSON file. Nothing is built to work for Key Vault yet, but I think the basic principle is there.

**Comment by newsroomdev** [comment]
Foundation added in #120, using `python-dotenv` to save credentials (including future potential Azure Key Vault access keys) to `env/.env`. The `env/` dir is already gitignored and can support additional secret filetypes, like Netscape HTTP cookies text files.
