### ISSUE TITLE
One-off: Livermore PD

### ISSUE THREAD

**Issue by newsroomdev** [biglocalnews/clean-scraper#138]
Using the MuckRock API, download assets related to Livermore PD and upload to Google Drive using `rclone` to the following file path, using keywords from the [CRP scraper projects spreadsheet](https://docs.google.com/spreadsheets/d/1PErZt4i34Ut1hZ_MGir0bRCH0ZUl_zOqBiOCYlbSSno/edit?gid=0#gid=0)

`f"case_files/{geo_slug}/{agency}/{current_date}/assets/{asset['case_id']}/{asset['name']}"`

This is a one-off script to retrieve assets that were already scraped

**Comment by tarakc02** [comment]
This was a one-off, and we have succesfully gotten the files and uploaded them to the case files dir
