### ISSUE TITLE
create clean/ca/sonoma_county_sheriff.py

### ISSUE THREAD

**Issue by ochezems** [biglocalnews/clean-scraper#24]
- agency slug (proposed): ca_sonoma_county_sheriff
- module: *clean/ca/sonoma_county.sheriff.py`
- url: https://www.sonomasheriff.org/sb1421

### Tasks
- [ ] find a way to update all detail page urls to autodownload link

### Scraping Plan

So far we've (Sophia and I) have found that if you alter dropbox links, you can download files directly. All of the detail page urls are in the main page's source code, so pulling them all should be straightforward, but we probably have to make a list/dict we can iterate on to update the links on the page to their downloadable forms ('dropbox.com/...../**d=1**').

**Comment by newsroomdev** [comment]
Closed with the merger of PR #34. Thank you!
