### ISSUE TITLE
YouTube links associated with scraped files?

### ISSUE THREAD

**Issue by ochezems** [biglocalnews/clean-scraper#33]
For #24, the scraper doesn't currently work on the youtube links of "Community Briefing Videos" on the page. Do we also need to be scraping these/collecting the links somewhere? Example below:

<img width="367" alt="Screenshot 2024-05-20 at 13 47 17" src="https://github.com/biglocalnews/clean-scraper/assets/165967112/200eed5f-8751-4efd-a597-1fe3ad314df5">

**Comment by kateyrusch644** [comment]
Yes. We also need to download these videos. If there is a way to keep track of what links have not been scraped, I can then go back and download the videos manually. Do you have a suggestion on how best to do that?

**Comment by ochezems** [comment]
The only videos that haven't been scraped are those labeled "Community Briefing Video"—these should all be youtube links but I can double check.
As for manually downloading.... well, the only way I ever downloaded youtube videos was thru shady sites named things like youtube-mp4.com (or something similar) as a kid. I can't on my school email endorse that behavior, but that's my experience :)

**Comment by newsroomdev** [comment]
closing in favor of newer issue

- #99
