### ISSUE TITLE
Dependency check

### ISSUE THREAD

**Issue by stucka** [biglocalnews/clean-scraper#47]
clean/utils.py uses `us` but that is not included in `requirements.txt`. It is included in `setup.py` ...

`requirements.txt` has a bunch of stuff not required in `setup.py` but I don't know what's actually needed vs. what's just specifying a version.

**Comment by stucka** [comment]
Pipfile is missing colorama

**Comment by stucka** [comment]
mypy is looking for typing for the module `us`, but I'm not seeing that one exists.

My pipenv wasn't installing `colorama` but I see it now in the Pipfile and I may have just been out of date.

**Comment by newsroomdev** [comment]
I believe this may have been fixed or updated with #60. Let me know if this issue is still relevant @stucka or if this is safe to close

**Comment by newsroomdev** [comment]
confirmed with @stucka this can be closed
