### ISSUE TITLE
Youtube video Downloader Not working

### ISSUE THREAD

**Issue by naumansharifwork** [biglocalnews/clean-scraper#76]
The Function that are used to download the videos from youtube are not working, I was working on corona_pd and it has some youtube links  which are unlisted links(means these videos are just accessed by direct links) when we use our existing function to download such videos it gives status code as 400. 

But i tried to download a video with a normal link and it gives this error:

Error fetching YouTube content: get_throttling_function_name: could not find match for multiple

I have search about this error and found it is raised on 9th july because youtube might have changed their javascript, 

This error can be fixed manually by replacing the function_patterns in cipher.py
function_patterns = [
        # https://github.com/ytdl-org/youtube-dl/issues/29326#issuecomment-865985377
        # https://github.com/yt-dlp/yt-dlp/commit/48416bc4a8f1d5ff07d5977659cb8ece7640dcd8
        # var Bpa = [iha];
        # ...
        # a.C && (b = a.get("n")) && (b = Bpa[0](b), a.set("n", b),
        # Bpa.length || iha("")) }};
        # In the above case, `iha` is the relevant function name
        r'a\.[a-zA-Z]\s*&&\s*\([a-z]\s*=\s*a\.get\("n"\)\)\s*&&.*?\|\|\s*([a-z]+)',
        r'\([a-z]\s*=\s*([a-zA-Z0-9$]+)(\[\d+\])?\([a-z]\)',
        r'\([a-z]\s*=\s*([a-zA-Z0-9$]+)(\[\d+\])\([a-z]\)',
    ]
    
but this does not solves the problem with unlisted youtube videos, so shall we look for alternative library for downloading youtube videos?

**Comment by newsroomdev** [comment]
Hi @naumansharifwork. I may update this library with a different Youtube Python library in the future after further evaluation and discussion. Let's hold off on that for now. Could you link to a branch to show me how you're using the `Cache.download` [method](https://github.com/biglocalnews/clean-scraper/blob/dev/clean/cache.py#L89)?

**Comment by naumansharifwork** [comment]
Hey @newsroomdev, #81  this is the one that is facing issue in youtube video download
